name: GPToolkit
main: rc.gpt.Loader
version: 1.0.0
author: RawCode
website: http://gamepolis.ru/forum/index.php?showforum=129
description: Custom classloader wrapper and utils for bukkit 172
load: startup